### ISSUE TITLE
🙏Please can I use this project?

### ISSUE THREAD

**Issue by killuazoldyckreal** [Ronnie-Reagan/WebRTC-Chat#1]
Thank you for sharing this WebRTC Chat project. I find it really helpful for learning WebRTC implementation. I really liked it since it contained the basic working implementation.

I noticed that the project is under a very strictly restricting <i><b>custom license</b></i>😞 on usage, including hosting or redistributing the code. I completely respect your rights as the author and the terms you’ve defined.

However, I would like to ask for explicit permission(🙏) to use this project for **personal**, **non-commercial purposes**. I will not sell, or use the project for any commercial purposes.

Please let me know if this would be acceptable😊👉👈. I truly appreciate❤ your work and look forward to your response.

**Comment by Ronnie-Reagan** [comment]
Hello @killuazoldyckreal,

Thank you for your kind words and appreciation of the project! I’m glad you found it helpful for learning WebRTC.

Regarding your request to use the project for personal, non-commercial purposes, I appreciate your respect for the license terms. At this time, the current license remains as written, and I’m not granting exceptions for personal or other uses beyond the provided service.

If you have questions about learning WebRTC or implementing similar functionality, I’d be happy to help point you toward resources or provide guidance where possible!

Thank you again for your understanding and interest.

Best regards,
Don Reagan
